### PR TITLE
Add data preparation

### PR DESCRIPTION
**Pull request by KingMaina**

### CODE REVIEW

**Review by deembuvi — APPROVED** [review]

**Review by Mercy-Ronoh — APPROVED** [review]
Changes for the file okay

**Comment by ashleySimiyu** [comment]
Good job

**Comment by KanyivaT** [comment]
Awesome job!!

**Review by EllahSidi — APPROVED** [review]
good one

**Review by ashleySimiyu — APPROVED** [review]

**Review by KanyivaT — APPROVED** [review]

**Pull request merged**
